blank_issues_enabled: true
contact_links:
  - name: qilindrop.cn Repository
    url: https://github.com/RobinLinus/snapdrop
    about: If you have encountered a general https://qilindrop.cn issue, please open a ticket in their repository.
